### ISSUE TITLE
ReferenceError: SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by tsafs** [tbolis/react-sketch#126]
Hi

Thanks for the module, it's been giving me a good idea of what I can do with the canvas. I will not be using this module anymore, but just found an error that you might be interested in.

It's occurring on the latest React version with the latest react-sketch version and only on the latest versions (probably also earlier versions) of Firefox, Firefox Mobile, Opera Mobile, others I haven't tested.

```
ReferenceError: SharedArrayBuffer is not defined
./node_modules/webidl-conversions/lib/index.js
C:/Users/Sebastian/Projects/Cards/client_new/node_modules/webidl-conversions/lib/index.js:347

  344 | 
  345 | const abByteLengthGetter =
  346 |     Object.getOwnPropertyDescriptor(ArrayBuffer.prototype, "byteLength").get;
> 347 | const sabByteLengthGetter =
  348 |     Object.getOwnPropertyDescriptor(SharedArrayBuffer.prototype, "byteLength").get;
  349 | 
  350 | function isNonSharedArrayBuffer(V) {
```

It is because those browsers do not support SharedArrayBuffer. 

I haven't dug deeper into the issue, because I'm dropping your module from my work, but here you go.

Happy hacking 👍

**Comment by amitnjha** [comment]
I am facing same error. It seems the component is not compatible with React 17, It works fine with React 16.

**Comment by scand1sk** [comment]
i ran the same error. I am still with React 16, for me it was triggered when I upgraded react-scripts to v4.x.x.

**Comment by scand1sk** [comment]
Upgrading react-sketch to 0.5.7 (using the npm module "react-sketch2") seems to have solved my issue.

**Comment by LaurentGENTY** [comment]
> Upgrading react-sketch to 0.5.7 (using the npm module "react-sketch2") seems to have solved my issue.

Solved issue too
