### ISSUE TITLE
Could react-sketch work on mobile platform?

### ISSUE THREAD

**Issue by Qquanwei** [tbolis/react-sketch#13]
Hi. Thank you for you work

I dont't know how to using react-sketch on mobile platform, or it have support mobile ?

**Comment by tbolis** [comment]
Hello Qquanwei and thank you for your comment,

This is a web application and will not work with a native mobile it requires canvas, I don't know if you wish to follow a route such as with cordova or a webview

Hope it helps

**Comment by Qquanwei** [comment]
I'll using in webview, 

in chrome device tools, i notice it won't be work

**Comment by zac18992** [comment]
Hey @Qquanwei I faced the same issue. It looks like the underlying library Fabric.js is having issues with touch support at the moment - https://github.com/kangax/fabric.js/issues/3869

**Comment by tbolis** [comment]
I have exposed a function enableTouchScroll in order to enable it on touch-based devices. simply do sketch.enableTouchScroll() to enable or sketch.disableTouchScroll() to disable

I have used sketchField at a react based application and cordova with success

**Comment by tbolis** [comment]
I'm closing the issue at the moment since it is more like a question - answer rather than an issue
