### ISSUE TITLE
when i  set defaultDataType = 'url' and set the defaultData   ,  it   doesn't  work , something wrong

### ISSUE THREAD

**Issue by ykx456654** [tbolis/react-sketch#15]
`
        if (defaultData) {
            if ('json' === defaultDataType) {
                this.fromJSON(defaultData);
            }
            if ('url' === defaultDataType) {
                this.fromDataURL(defaultData);   
               // there in no  method named "fromDataURL"， is it  "setBackgroundFromDataUrl"?
            }
        }
`

sorry , my English is poor.

**Comment by fjogeleit** [comment]
Fix this problem in my Fork / in my PR: https://github.com/fjogeleit/react-sketch

You can build this version without any cairo dependencies

**Comment by tbolis** [comment]
same reason with issue #10
