### ISSUE TITLE
TypeError: Cannot read property 'offsetWidth' of null

### ISSUE THREAD

**Issue by kylefoley** [tbolis/react-sketch#16]
Upgraded to React 16, getting this error and react-sketch will not load. Any advice on this? Thanks!

**Comment by kylefoley** [comment]
Anyone else having this issue after upgrading to React 16.0.0?

**Comment by fjogeleit** [comment]
i create an Pull Request for React v16.0 compability. You can use this fork to build and use it in your project.

**Comment by kylefoley** [comment]
Can't get it to do a npm install on Windows for some reason, but I don't think it's the repo's issue. I'll just have to wait until @tbolis accepts your pull request. Thanks!

**Comment by kylefoley** [comment]
Having issues doing `npm install` in the dir. Getting a lot of "unexpected token"s in SketchField and in the tests. Any advice on how to build this?

**Comment by fjogeleit** [comment]
@kylefoley at this link you will find the build version of my fork:
https://gist.github.com/fjogeleit/cb7ed3b636b2207c756ae72c51cb428b

could you link a screen of your build error?

**Comment by kylefoley** [comment]
Oh perfect, it looks like I was just doing it incorrectly. Thank you for your help @fjogeleit, it works great!
