### ISSUE TITLE
Add Text Functionality

### ISSUE THREAD

**Issue by inf3cti0n95** [tbolis/react-sketch#24]
Adding Text to the Canvas

**Comment by Asthonishia** [comment]
What about this ? Same need here

**Comment by inf3cti0n95** [comment]
I've added a PR. But, @tbolis seems to be on a hiatus.

**Comment by Asthonishia** [comment]
:(

**Comment by inf3cti0n95** [comment]
Meanwhile you could use [my fork](https://github.com/inf3cti0n95/react-sketch) for the Add Text feat.

**Comment by tbolis** [comment]
New release includes basic text functionality. @inf3cti0n95 very creative comment indeed

**Comment by inf3cti0n95** [comment]
Hehe, I had even emailed you about the project. Good thing that you are back!
