### ISSUE TITLE
Use image as canvas background

### ISSUE THREAD

**Issue by jankoritak** [tbolis/react-sketch#27]
Hi,

is there currectly any way to use image as an canvas background?

**Comment by jankoritak** [comment]
Oops, just realised sketch has `sketch.setBackgroundFromDataUrl`.

Closing this.

**Comment by tbolis** [comment]
Hi,

yes, there is, as you found out. Pls, also you check the showcase I have here: 

http://tbolis.github.io/showcase/react-sketch/

T.

**Comment by Santosh-webllisto** [comment]
how can i add background image in react.(which prop do i have to use)

**Comment by agaertner** [comment]
hey is there a way to also clear the backgroundImage?
clear() seems to only remove drawn content. Edit: Passing null to .setBackgroundFromDataUrl() seems to have done the trick I believe.
