### ISSUE TITLE
jsdom is not a function

### ISSUE THREAD

**Issue by iamMonzurul** [tbolis/react-sketch#28]
Hi,
I am having an issue.
`
TypeError: __webpack_require__(...).jsdom is not a function`

**Comment by tbolis** [comment]
Hi there, 

this sounds like some short of babel/configuration issue. Is it possible to use the same versions and set of libraries as I have in the example (.babelrc, package.json etc.)?

Thanks for tying my component, let me know

**Comment by tlouth19** [comment]
I'm having the same issue as well using both gatsby and react-static. It builds properly in development but the production build fails with the same error

**Comment by iamMonzurul** [comment]
I have tried with your babelrc plugin setup but still having this issue. Could you please tell me anything more?

**Comment by tbolis** [comment]
Will be upgrading to latest version of babel/webpack so hopefully this will be resolved as well

**Comment by Egrace** [comment]
Hi! I got the same problem with `jsdom`
```
Module not found: Error: Can't resolve 'jsdom' in 'path/to/my/project/node_modules/react-sketch/dist'
```

**Comment by emmanuelle** [comment]
I have the same problem as @Egrace (it appeared when I tried to upgrade from version 0.4.4 to 0.5.1).

**Comment by yashikagarg13** [comment]
@tbolis I am still facing the issue with version 0.5.1. Is there any workaround?

**Comment by Prior99** [comment]
I am experiencing the same issue.
