### ISSUE TITLE
lib folder not installing with npm install

### ISSUE THREAD

**Issue by KyleFoleyImajion** [tbolis/react-sketch#29]
Recently updated to 0.4.2, it removed my lib folder from node_modules/react-sketch and I can't get it back. I tried to downgrade to 0.4.0 and it still won't install a lib folder. I have duplicated this on two computers. Has anyone else seen this issue? Thanks

**Comment by tbolis** [comment]
Looking into it thanks

**Comment by tbolis** [comment]
it is fixed with 0.4.4 sorry for this inconvenience

**Comment by KyleFoleyImajion** [comment]
Not a problem at all. 0.4.4 works on my side. Thank you for the quick response time!
