### ISSUE TITLE
React-Sketch not Uglifying/Minifying in webpack.

### ISSUE THREAD

**Issue by sjorsvanheuveln** [tbolis/react-sketch#31]
Hey there,

I just noticed when I was building my app to production mode that this module is not being uglified? Do you have any idea why this could be?

<img width="1280" alt="react-sketch is not being minified" src="https://user-images.githubusercontent.com/13645429/36456273-5fb4bb18-16a4-11e8-8b50-dc02a2c3343d.png">
As you can see, the stat-size and parsed-size are identical, meaning they didn't get minified. All the other modules in project are being minified, so there's something going on with this module.

**Comment by sjorsvanheuveln** [comment]
Could anyone confirm this?

**Comment by tbolis** [comment]
@sjorsvanheuveln doing my best :)

The `index.js` is a bulk with fabric lib and is at 365 KB on disk. If you open/see the file is aready minified

Any suggestions are welcome

Thank you for your info
