### ISSUE TITLE
PhantomJS PATH not found (deploying to production)

### ISSUE THREAD

**Issue by shafy** [tbolis/react-sketch#35]
While it works fine locally, when I try to deploy to production on Heroku it throws the following error:

```
PhantomJS not found on PATH
remote:        Phantom installation failed TypeError: Path must be a string. Received undefined
```

I use react-create-app and the https://github.com/mars/create-react-app-buildpack.git build pack on Heroku with yarn.

Any ideas?

**Comment by shafy** [comment]
I did some research and it seems like the issue is resolved in `phantomjs-prebuilt@2.1.8` - @tbolis could you try updating that?

**Comment by datpham23** [comment]
+1 
Can we upgrade phantomjs-prebuilt?

**Comment by slevy85** [comment]
With npm the build seems to work anyway, but I have the same error using yarn.

With yarn we can force the build to use a newer version : 
in package.json
```
  "resolutions": {
    "react-sketch/**/phantomjs-prebuilt": "2.1.8"
  }
```
The build now works good

**Comment by tbolis** [comment]
I'm preparing a new version where I removed phantom and I use jest, stay tuned
