### ISSUE TITLE
How to remove a selected item?

### ISSUE THREAD

**Issue by sjorsvanheuveln** [tbolis/react-sketch#36]
Which methods to perform if I want to delete a selected item in the canvas. I can acces undo and redo, so I guess it should be possible to delete a selected item. But how?

**Comment by Asthonishia** [comment]
Same question

**Comment by tbolis** [comment]
Will be releasing a new version very soon, where I implement the requested functionality! Stay tuned

**Comment by jwillingham789** [comment]
I see this was added in the newest version, however, I don't see how to do it in the docs. Can you explain? Thanks!

**Comment by tbolis** [comment]
hi sorry for this,

You can also play with the examples: http://tbolis.github.io/showcase/react-sketch/

You select the `select tool` select the object you want to delete and then you hit remove or invoke the `sketchComponent.remove()`

On my second card I have at the bottom the control buttons

Hope it helps (and will update the docs soon :) )

**Comment by xadamxk** [comment]
I know the last commit was nearly a year ago, but is there any update on the documentation to delete an object?
