### ISSUE TITLE
how can I add undo/redo

### ISSUE THREAD

**Issue by harshitnayak45** [tbolis/react-sketch#41]
hi thanks for the awesome package for sketch I wan to integrate undo/redo but I unable to know how can i do this.

**Comment by tbolis** [comment]
Hi 

Thank you for your awesome words, you can find what you are asking at the example, check here

`https://github.com/tbolis/react-sketch/blob/43e0326ae548e405af1ccde5c6bf834d69e1e927/examples/main.jsx#L177`

**Comment by tbolis** [comment]
Closing this as it is a question rather than an issue
