### ISSUE TITLE
Resize canvas width and height to match backgroundImage dimensions

### ISSUE THREAD

**Issue by emmanuelle** [tbolis/react-sketch#46]
Thanks for a great package! Is there a way to resize automatically the canvas when a background image is loaded, so that the dimensions of the canvas (width and height) match the ones of the background image? One solution I can see is to retrieve the content using the toJSON method, and then accessing the width and height of the background image. Or is there another recommended way to do this?

**Comment by AubertK** [comment]
Hi, 
You have to set OriginX and OriginY to false:
`reader.addEventListener('load', () => sketch.setBackgroundFromDataUrl(reader.result, {                
			stretched: stretched,
            stretchedX: stretchedX,
            stretchedY: stretchedY,
            originX: false,
            originY: false
		}), false);`
Hope its helping you,
Have a good day !
