### ISSUE TITLE
Multiple SketchField components

### ISSUE THREAD

**Issue by patatjenl** [tbolis/react-sketch#5]
Hi! Is it possible to support multiple SketchField components?
Currently, it seems like the second one does not get initialized.

```js
class SketchFieldDemo extends React.Component {
     render() {
        return (
            <div>
                 <SketchField width='1024px' 
                              height='768px' 
                              tool={Tools.Pencil} 
                              color='black'
                              lineWidth={3}/>
                 <SketchField width='1024px' 
                              height='768px' 
                              tool={Tools.Pencil} 
                              color='black'
                              lineWidth={3}/>
            </div>
        )
     }
}
```

**Comment by bolist** [comment]
Hi @patatjenl thanks for trying it out. I just launch it with two sketch fields and everything works normally.. Can you give me some details, an error at the console maybe to help me?
Thx

**Comment by patatjenl** [comment]
I've tried the same in the example folder files and it works perfectly, which means it has to be a problem in my code, somewhere. Thank you for the quick response, if I've got any further trouble I'll reopen the issue.

**Comment by tbolis** [comment]
super!
Thx @patatjenl

**Comment by patatjenl** [comment]
To share my solution to this problem: After looking through the project files for the solution, I checked the packages. As [Material-UI](http://www.material-ui.com/) started giving the interesting [`Warning: Unknown prop` notices](https://github.com/callemall/material-ui/issues/4670), I never updated the React package. After I did, React-Sketch worked as expected. 👍

**Comment by yadavendra15** [comment]
Hey @winfried-van-loon,

I'm getting the same issue with the MUI tabs.
And it seems like the whiteboard is not initialised.. 

Its shows me width and height 0, looks like the whiteboard is not rendered.

Please can you help me with my code in codesandbox 
https://codesandbox.io/s/goofy-wozniak-hyy8k?file=/src/LLWhiteBoardTabs.js

**Comment by winfried-van-loon** [comment]
Sorry, I cannot help, it is way too long ago. Please, open a new issue.
