### ISSUE TITLE
How to access mouse Events? onMouseUp and onMouseDown, to get coordinates.

### ISSUE THREAD

**Issue by dushyanttessact** [tbolis/react-sketch#68]
I want to get mouse coordinates onMouseUp and onMouseDown events, so that i can replicate the design in another screen. @tbolis @karlvr @shafy @afilp

**Comment by CentroneF** [comment]
Hi, 

I had similar issue. You are able to export the drawing as DataUrl and set it as a background in an other React-sketch application (in your case screen). 

Check the demo application. There is a way to download the drawing as dataUrl. To import you can use `.setBackgroundFromDataUrl` in the SketchField component reference.

I hope it was useful.
Good luck
