### ISSUE TITLE
How to upload a large background image and auto fit for the sketch area?

### ISSUE THREAD

**Issue by issac1024623** [tbolis/react-sketch#69]
First of all, it is a great package in drawing in react.
I wonder how can I upload an image which is larger than the sketch area.
Let say I need to put a 600x400 image as a background of 300x300 area

I follow the example to use the code below to change background image:

reader.addEventListener(
        'load',
        () =>
          sketch.setBackgroundFromDataUrl(reader.result, {
            stretched: stretched,
            stretchedX: stretchedX,
            stretchedY: stretchedY,
            originX: originX,
            originY: originY,
          }),
        false,
      );

I assume the stretched props will make something different. However, it didnt. Even the example in http://tbolis.github.io/showcase/react-sketch/ , I cannot see the whole image when a upload a large background image. 
Please Help, Thanks

**Comment by emmanuelle** [comment]
Hi @issac1024623, instead of a background image you can use the ``addImg`` method (which adds an image as an element of the canvas, not as a background) https://github.com/tbolis/react-sketch/blob/master/src/SketchField.jsx#L120. You can pass a scale parameter as one of the options. For example I used it in my dash-canvas project https://github.com/plotly/dash-canvas/blob/master/src/lib/components/DashCanvas.react.js#L52.
Hope this helps!

**Comment by issac1024623** [comment]
Thanks for answering my question, it works now. 
However, I encountered another problem. I dont know whether it is a bug or I did something wrong
![Screenshot 2019-03-29 at 10 04 38 AM](https://user-images.githubusercontent.com/15829696/55204541-4eff1000-520a-11e9-82a5-8eeb1cb307d1.png)
sometime when I sketch on it. The line will become blur. I have no idea on this.
Have you face this problem before?
Thanks for your time.

**Comment by emmanuelle** [comment]
I never had this problem but maybe other users did and can help you. Could you please tell us what are the parameters (lineWidth, tool, etc.) when this problem happens?

**Comment by issac1024623** [comment]
What I implemented is 

 <SketchField width={this.state.sketchWidth}
            height={this.state.sketchHeight}
            ref={c => (this.sketch = c)}
            tool={Tools.Pencil}
            lineColor={this.state.lineColor}
            lineWidth={this.state.lineWidth}
            backgroundColor={this.state.sketchBackgroundColor}
            onChange={()=>this.onSketchChange()}
          />

And here is my initial state of mySketch
this.state = {
      stretched: false,
      stretchedX: false,
      stretchedY: false,
      originX: 'left',
      originY: 'top',
      sketchWidth: 400,
      sketchHeight: 400,
      sketchBackgroundColor: 'white',
      lineColor: 'black',
      lineWidth: 3,
      value: 5,
      colorDropdownOpen: false,
      bgColorDropdownOpen: false,
      drawings: [],
      canUndo: false,
      canRedo: false,
    }

Is there are something I missed in <SketchField/> ?

**Comment by wingclover** [comment]
> Thanks for answering my question, it works now.
> However, I encountered another problem. I dont know whether it is a bug or I did something wrong
> ![Screenshot 2019-03-29 at 10 04 38 AM](https://user-images.githubusercontent.com/15829696/55204541-4eff1000-520a-11e9-82a5-8eeb1cb307d1.png)
> sometime when I sketch on it. The line will become blur. I have no idea on this.
> Have you face this problem before?
> Thanks for your time.

I also have this problem. It happens when I draw a line that's not horizontal or vertical. 45 degrees are the worst. Didn't figure out why or how to fix.

**Comment by issac1024623** [comment]
I should open a new issue for this problem
To attract somebody to help
