### ISSUE TITLE
Have the option of making the sketchfield resize on other events than window resize

### ISSUE THREAD

**Issue by FerusAndBeyond** [tbolis/react-sketch#7]
I wanted to have a resizable sketch field but when I resize it (change height and width props of SketchField) the canvas stays the same size. To make it work I had to manually trigger the resize event of window. Like this:

```
    componentDidUpdate: function () {
        var sketch = this.refs.sketch;
        var style = this.props.style;
        if (style.width !== sketch._canvas.clientWidth || style.height !== sketch._canvas.clientHeight) {
            window.dispatchEvent(new Event("resize"));
        }
    },
```

**Comment by tbolis** [comment]
Dear @FerusAndBeyond thank you for your input, I have resolved the issue by adding controlled properties width and height, please check if possible and let me know if it is ok, you can see the example page  as well.

**Comment by FerusAndBeyond** [comment]
Changing width and height works perfectly now, thanks! Though unless I did something wrong I noticed 2 issues when height and width are _not_ specified. The height is set to 512 by this statement:

` let canvasDivStyle = Object.assign({}, style ? style : {}, width ? {width: width} : {}, height ? {height: height} : {height: 512});`

Changing height:512 to {} removed this issue. Also in the configuration options it says if you leave height/width empty it will scale to parent but that does not seem to be the case for me.

**Comment by tbolis** [comment]
Yes you are right, I have added a reasonable default value for height, I will correct the documentation. The other option would be to leave it blank and will automatically scale to parent height as well, but this would mean that to use the component you would have to be careful to strictly define the parent height. 
Besides you can achieve the controlled width and height by supporting it with your own code as a controlled component (with higher order composition etc.)

Hope it helps

**Comment by FerusAndBeyond** [comment]
Yes I understand, I was just confused by the documentation.

**Comment by tbolis** [comment]
Cool thx, hope you like the new feature/bug fix
