### ISSUE TITLE
Controlling the data from parent-component/props

### ISSUE THREAD

**Issue by FerusAndBeyond** [tbolis/react-sketch#9]
A nice feature would be to able to control the sketch-data from the parent-component/props. This way two persons can draw together by sharing and mutating external data for example.

Adding this to componentWillReceiveProps, could be a quick solution:

```
if(defaultData) {
            if ('json' === defaultDataType) {
                this.fromJSON(defaultData);
            }
            if ('url' === defaultDataType) {
                this.fromDataURL(defaultData);
            }
}

```

or maybe have another prop?

**Comment by tbolis** [comment]
fixing this with version 4 onwards
